language: go
sudo: true
matrix:
  include:
    - go: "1.2"
      before_install:
        - go get code.google.com/p/go.tools/cmd/cover
        - go get code.google.com/p/go.tools/cmd/goimports
    - go: "1.3"
      before_install:
        - go get code.google.com/p/go.tools/cmd/cover
        - go get code.google.com/p/go.tools/cmd/goimports
    - go: "1.4"
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get golang.org/x/tools/cmd/goimports
    - go: "tip"
      before_install:
        - go get golang.org/x/tools/cmd/cover
        - go get golang.org/x/tools/cmd/goimports
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y debconf-utils
  - sudo debconf-set-sellections testdata/debconf.txt
  - sudo DEBCONF_FRONTEND=noninteractive apt-get -y --force-yes install slapd
  - sudo apt-get install -y ldap-utils ldapvi
  - sudo ldapadd -H ldapi:/// -Y EXTERNAL -f testdata/openssh-lpk.ldif
  - sudo ldapmodify -H ldapi:/// -Y EXTERNAL -f testdata/rootdnpw.ldif
  - ldapadd -x -h localhost -D cn=admin,dc=example,dc=org -w password -f testdata/ou.ldif
  - ldapadd -x -h localhost -D cn=admin,dc=example,dc=org -w password -f testdata/users.ldif
  - go get github.com/mattn/goveralls
  - go get -d -v ./...
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
